# Generated by Django 4.1 on 2022-08-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="Password",
            field=models.CharField(default="1234", max_length=6),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(default="male", max_length=10),
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default="username", max_length=10),
        ),
    ]
