# Generated by Django 4.1 on 2022-08-25 17:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_alter_user_gender"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task", old_name="task_content", new_name="content",
        ),
        migrations.AddField(
            model_name="task",
            name="target_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="target_time",
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="title",
            field=models.CharField(default="title", max_length=30),
            preserve_default=False,
        ),
    ]
