# Generated by Django 4.1 on 2022-09-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_alter_task_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("Completed", "Completed"),
                    ("In Progress", "In Progress"),
                    ("Yet to start", "Yet to start"),
                ],
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="task", name="content", field=models.TextField(max_length=200),
        ),
    ]
